### ISSUE TITLE
Cannot delete last byte in file

### ISSUE THREAD

**Issue by dbrgn** [Luz/hexdino#11]
Steps to reproduce:

$ echo "hello" > test.dat
$ hexdino test.dat

Then navigate over last byte (`0A`) and press `x` to delete. Then enter `:wq` to save and quit.

Open the file again with hexdino, the `0A` byte is still there.

**Comment by Luz** [comment]
This is because the current "file write" only copies the buffer to the file, beginning from the start of the file (and buffer).
When the file size is bigger than the buffer, the rest of the file does not get changed.
The problem will be fixed, when the rest of the file gets deleted after a successful write.

**Comment by dbrgn** [comment]
Ah, I see! :)
